Species.destroy_all

Species.create({name: "Unknown"})
Species.create({name: "Oak"})
Species.create({name: "Maple"})
Species.create({name: "Elm"})
Species.create({name: "Pistache"})
Species.create({name: "Sycamore"})
Species.create({name: "Ginkgo"})
Species.create({name: "Redwood"})
Species.create({name: "Cherry"})
Species.create({name: "Locust"})
Species.create({name: "Yew"})
Species.create({name: "Chestnut"})
Species.create({name: "Laurel"})
Species.create({name: "Almond"})
Species.create({name: "Walnut"})
Species.create({name: "Pecan"})
Species.create({name: "Willow"})
Species.create({name: "Apple"})
Species.create({name: "Citrus"})
Species.create({name: "Plum"})
Species.create({name: "Palm"})